### ISSUE TITLE
Improve WxIF's repository information

### ISSUE THREAD

**Issue by Eagle3386** [gcp/wxif#11]
@gcp, I'd like to suggest 3 improvements for your repository:
1. Add a link to the add-on's AMO page (https://addons.mozilla.org/addon/wxif/), right beside your repository description. 
   - **Note:** using this exact link, AMO does the language-detection for us

2. Change the repository description from
   > WebExtensions port of the FxIF EXIF reader.

   to
   > WebExtensions port of FxIF for reading EXIF information from JPEG files.
3. Add topics to the repository, e. g. `firefox-webextension` and `exif-reader` for easier discovery by users, search engines, etc.

You can find a demo in my [forked repository](https://github.com/Eagle3386/wxif). 😉

**Comment by gcp** [comment]
Thanks for the suggestions. I incorporated them.

**Comment by Eagle3386** [comment]
You're welcome! 😃

As soon as there's more leisure time on my end, I'll dig deeper into WxIF's code to provide (more) code, too.
