### ISSUE TITLE
Blank window on Linux, until resized

### ISSUE THREAD

**Issue by fisherhu** [gcp/wxif#3]
In Firefox 57.0b7 (Quantum, beta atm) the window is empty. Not sure if it is a real bug or just due the beta Firefox.
Example image: https://blog.fisher.hu/blogv1/wp-uploads/2015/04/DSCN6118-copy.jpg

**Comment by gcp** [comment]
This is due to a regression/breaking change in Firefox. We're investigating in [Mozilla bug 1408446](https://bugzilla.mozilla.org/show_bug.cgi?id=1408446)

**Comment by Smile4ever** [comment]
The bug was fixed by enabling out-of-process extensions on Linux. See the bugzilla bug. I verified it works in Firefox Nightly, so I think this bug can be closed now.
