### ISSUE TITLE
Report as requested

### ISSUE THREAD

**Issue by Studio-Dee** [gcp/wxif#6]
Image ExiF reports an error and request that one reports it, so here it is.

Make | RICOH IMAGING COMPANY, LTD.
-- | --
Model | PENTAX 645Z
Software | Adobe Photoshop Lightroom Classic 7.0 (Macintosh)
Creator | ROY CLARKE
Copyright | STUDIO-DEE 07818 018534
Exposure Time | 0.0025s (1/400)
Aperture | ƒ/8.0
Exposure | shutter priority (semi-auto)
ISO equivalent | 200
Exposure Bias | none
Metering Mode | Center Weight
Flash Fired | No (enforced)
Focal Length | 80.0mm 62mm=35mm equivalent
Color Space | sRGB
FocalPlaneXRes | 1876.3636474609375
FocalPlaneUnits | 10
White Balance | Auto
Focal Length (35mm) | 62
LensModel | smc PENTAX-FA645 80-160mm F4.5
Date | 2017-10-21 12:41:31 (no TZ)
Lens | smc PENTAX-FA645 80-160mm F4.5
error | XMP,XMPError  while interpreting %S data. %S meta data shown might be not complete.  Please report this problem with an example image. TypeError:  parser.parseFromBuffer is not a function

The particular image is attached
![_dee1680-1713-1714](https://user-images.githubusercontent.com/33750969/32944462-8cc790c0-cb87-11e7-92fd-046a32dee762.jpg)

**Comment by gcp** [comment]
See issue #1.

I probably won't get around to fixing such things myself, but keeping track of them will help whoever decides to take that up.
